### ISSUE TITLE
Device is able to be found but unable to connect to miditran

### ISSUE THREAD

**Issue by jjwall** [xobs/midi-to-keypress#4]
![issue](https://user-images.githubusercontent.com/22758295/88756175-7e889a00-d128-11ea-9494-50d71032bca7.PNG)

**Comment by xobs** [comment]
Thanks for the report!

It looks like the `midir` crate I use to handle MIDI doesn't pass along the reason for the failure, which seems like a shortcoming. It looks like it calls the Windows API function `midiInOpen()`, which can generate the following failure reasons:

https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midiinopen#return-value

Value | Description
-- | --
MMSYSERR_ALLOCATED | The specified resource is already allocated.
MMSYSERR_BADDEVICEID | The specified device identifier is out of range.
MMSYSERR_INVALFLAG | The flags specified by dwFlags are invalid.
MMSYSERR_INVALPARAM | The specified pointer or structure is invalid.
MMSYSERR_NOMEM | The system is unable to allocate or lock memory.

I've opened an issue on `midir` to report more useful error messages (https://github.com/Boddlnagg/midir/issues/64), but in looking at the list I can think of two reasons that could cause this failure:

1. The device is already open in another program, such as a DAW
2. The string contains space padding (or other nonprintable characters) that is important in matching the name.

Can you please see if the device is open in another program?

Can you please also omit the `--device` argument? If you don't specify a device, it will pick the first one it finds, and in your case that's the only device on the system.

**Comment by jjwall** [comment]
Wow that was a quick reply! Yes you were exactly right! I had the device open in another program. Specifying the device or calling ``miditran`` directly works too! 

Edit: Do you have any plans to add external configurations?

Edit2: I see some recent commits for adding mapping files. I'll build the source code and see if it's operational!
