### ISSUE TITLE
Instructions for running in Proton under Linux

### ISSUE THREAD

**Issue by linkous8** [xobs/midi-to-keypress#6]
Hey, I was curious if you have any recommendations as to getting this running inside the proton environment (or if I can just compile the exe for linux and use it that way). If not, I'll update this ticket with a solution once I get around to researching and figuring it out.

**Comment by xobs** [comment]
You should be able to build this on Linux by simply running `cargo run`. I'd be open to CI pulls to build it on other platforms!

I was careful to select binaries with cross-platform support, so I'd be curious to know whether it works at all.

**Comment by kyren** [comment]
AFAICT it works as intended on linux with proton.

This situation may change if / when proton uses wayland?

**Comment by linkous8** [comment]
Thanks for verifying @kyren !
